name: Sung-Soo Kim's Blog
source: .
destination: ./posthtml
markdown: redcarpet
pygments: true
baseurl: sungsoo.github.io
paginate: 7
comments :
    provider : disqus
    disqus :
      short_name : sungsoo